image: python:latest

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  PIPENV_CACHE_DIR: $CI_PROJECT_DIR/.cache/pipenv


stages:
  - build
  - test

cache:
  key: uplyfile
  paths:
    - .cache/pip
    - .cache/pipenv
    - .venv/

build:
    stage: build
    variables:
        PIPENV_VENV_IN_PROJECT: "true"

    script:
        - echo "PIPENV BUILD ENV"
        - pip install pipenv
        - pipenv sync --clear

black:
   stage: test
   script:
     - echo "BLACK"
     - source .venv/bin/activate
     - black --check uplyfile_django/*.py


pytest:
    stage: test
    variables:
        DJANGO_SETTINGS_MODULE: "uplyfile_django.tests.test_settings"
    script:
        - echo "PYTEST"
        - source .venv/bin/activate
        - python ./runner.py
