image: python:latest

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  PIPENV_CACHE_DIR: $CI_PROJECT_DIR/.cache/pipenv


stages:
  - build
  - black
  - test

cache:
  paths:
    - .cache/
    - .venv/

build:
    stage: build
    script:
        - echo "PIPENV BUILD ENV"
        - pip install pipenv
        - export PIPENV_VENV_IN_PROJECT=True
        - pipenv install --skip-lock


black:
    stage: black
    script:
        - echo "BLACK - syntax checking"
        - source .venv/bin/activate
        - black --check uplyfile_django/*.py

test:
    variables: 
      DJANGO_SETTINGS_MODULE: "uplyfile_django.tests.test_settings"
    script:
        - echo "PYTEST - testing software"
        - source .venv/bin/activate
        - pytest
