repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    -    id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    -    id: flake8
         args: [--ignore=E501]
    -    id: check-ast
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.8.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.17
    hooks:
    -    id: isort
         args: [-y]
